### ISSUE TITLE
Could You Release The Trainning Source Code ?

### ISSUE THREAD

**Issue by siyaofa** [galbiati/mtcnn#10]
The model works fine for me!
I use the Net find face from camera, most position recognized good .
I'm wondering if that's possible , you release the trainning part.
Cause I want to trainning my own model, not detect face.

**Comment by galbiati** [comment]
I didn't do any training. I mainly wanted to keep NMS in PyTorch and provide a more convenient packaging.

The weights I used came from a different implementation [here](https://github.com/TropComplique/mtcnn-pytorch). It looks like the author did not train either, just pulled the weights from a Caffe model. 

You can find the original project [here](https://github.com/kpzhang93/MTCNN_face_detection_alignment), but I'm not sure the original author published training code either.

Anyway, good luck!

**Comment by siyaofa** [comment]
The original project only have pretrained model. Author did not release training part.
I guess three maybe some magic tricks in trainning .
